// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	Token     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	RevokedAt sql.NullTime
	UserID    string
	ExpiresAt time.Time
}

type User struct {
	ID        string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Password  string
	Email     string
}

type Video struct {
	ID           string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	Title        string
	Description  sql.NullString
	ThumbnailUrl sql.NullString
	VideoUrl     interface{}
	UserID       sql.NullString
}
