// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: q_CreateVideo.sql

package database

import (
	"context"
	"database/sql"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (
    id,
    created_at,
    updated_at,
    title,
    description,
    user_id
)
VALUES (?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?, ?, ?)
RETURNING id, created_at, updated_at, title, description, thumbnail_url, video_url, user_id
`

type CreateVideoParams struct {
	ID          string
	Title       string
	Description sql.NullString
	UserID      sql.NullString
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.UserID,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.ThumbnailUrl,
		&i.VideoUrl,
		&i.UserID,
	)
	return i, err
}
