// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: q_CreateUser.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users
(id, created_at, updated_at, email, password)
VALUES
(?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, ?, ?)
RETURNING id, created_at, updated_at, password, email
`

type CreateUserParams struct {
	ID       string
	Email    string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
		&i.Email,
	)
	return i, err
}
