// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: q_DeleteRefreshToken.sql

package database

import (
	"context"
)

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec

DELETE FROM refresh_tokens
WHERE token = ?
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshToken, token)
	return err
}
