// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: q_DeleteVideo.sql

package database

import (
	"context"
)

const deleteVideo = `-- name: DeleteVideo :exec
DELETE FROM videos
WHERE id = ?
`

func (q *Queries) DeleteVideo(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteVideo, id)
	return err
}
