// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: q_GetUser.sql

package database

import (
	"context"
	"database/sql"
)

const getUser = `-- name: GetUser :one
SELECT id, created_at, updated_at, email, password
FROM users
WHERE id = ?
`

type GetUserRow struct {
	ID        string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Email     string
	Password  string
}

func (q *Queries) GetUser(ctx context.Context, id string) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
	)
	return i, err
}
