// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: q_GetVideos.sql

package database

import (
	"context"
	"database/sql"
)

const getVideos = `-- name: GetVideos :many
SELECT
    id,
    created_at,
    updated_at,
    title,
    description,
    thumbnail_url,
    video_url,
    user_id
FROM videos
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetVideos(ctx context.Context, userID sql.NullString) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, getVideos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Description,
			&i.ThumbnailUrl,
			&i.VideoUrl,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
