// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: q_GetUserByRefreshToken.sql

package database

import (
	"context"
	"database/sql"
)

const getUserByRefreshToken = `-- name: GetUserByRefreshToken :one
SELECT u.id, u.email, u.created_at, u.updated_at, u.password
FROM users u
JOIN refresh_tokens rt ON u.id = rt.user_id
WHERE rt.token = ?
`

type GetUserByRefreshTokenRow struct {
	ID        string
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Password  string
}

func (q *Queries) GetUserByRefreshToken(ctx context.Context, token string) (GetUserByRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByRefreshToken, token)
	var i GetUserByRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Password,
	)
	return i, err
}
