// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: q_GetVideo.sql

package database

import (
	"context"
)

const getVideo = `-- name: GetVideo :one
SELECT
    id,
    created_at,
    updated_at,
    title,
    description,
    thumbnail_url,
    video_url,
    user_id
FROM videos
WHERE id = ?
`

func (q *Queries) GetVideo(ctx context.Context, id string) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
		&i.ThumbnailUrl,
		&i.VideoUrl,
		&i.UserID,
	)
	return i, err
}
