// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: q_UpdateVideo.sql

package database

import (
	"context"
	"database/sql"
)

const updateVideo = `-- name: UpdateVideo :exec
UPDATE videos
SET
    updated_at = CURRENT_TIMESTAMP,
    title = ?,
    description = ?,
    thumbnail_url = ?,
    video_url = ?,
    user_id = ?
WHERE id = ?
`

type UpdateVideoParams struct {
	Title        string
	Description  sql.NullString
	ThumbnailUrl sql.NullString
	VideoUrl     interface{}
	UserID       sql.NullString
	ID           string
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) error {
	_, err := q.db.ExecContext(ctx, updateVideo,
		arg.Title,
		arg.Description,
		arg.ThumbnailUrl,
		arg.VideoUrl,
		arg.UserID,
		arg.ID,
	)
	return err
}
