-- +goose Up
CREATE TABLE IF NOT EXISTS users (
	id TEXT PRIMARY KEY,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	password TEXT NOT NULL,
	email TEXT UNIQUE NOT NULL
);

-- +goose Down
DROP TABLE users;